### ISSUE TITLE
"Error":"Access denied."

### ISSUE THREAD

**Issue by MarErm27** [cv3/QuickBooksWebConnector#1]
`{"Error":"Access denied.","Json":"{\"CV3Data\":{\"error\":\"Access denied.\"}}","level":"error","msg":"Error in CV3 order return","time":"2020-05-31T21:07:12+03:00"}`

Hello! I was wondering if this brilliant QuickBooks Web Connector implementation may be used for custom purposes? What needs to be changed? How to fix the error? The idea to write it is in GO is just fantastic

**Comment by pageben** [comment]
Hello!  Glad you're excited about this repo!

This is an open source project and uses the [GNU Affero General Public License](https://github.com/cv3/QuickBooksWebConnector/blob/master/LICENSE).  Be sure to read through it so you can understand the permissions, limitations, and conditions of using the source in your custom project.

Are you a [CommerceV3](https://www.commercev3.com/) client?  The error that you're seeing is likely due to the software not being able to communicate with the CV3 webservice.  If you are a CV3 client, get in touch with your customer service representative and they'll help you get QBWC connected.  The readme on this project includes an Installation Guide.  It sounds like you'll want to go through the steps [here](https://github.com/cv3/QuickBooksWebConnector#configure-the-quickbooks-web-connector-with-the-cv3-integration-server).

If you're not a CommerceV3 client and you're trying to customize the software to connect with another order management system, search for the function InitWork.  It calls GetCV3Orders(), which is intended to pull orders from CV3's webservice.  You'll want to replace func GetCV3Orders with  your own custom code that uses whatever API you're connecting to.

**Comment by MarErm27** [comment]
@pageben May I ask which functions responsible for getting invoices and items from web service?

**Comment by pageben** [comment]
In /qbwcGo/qbwcGetCV3Orders.go , look for func GetCV3Orders().
It pulls pending order information from CV3 for QBWC to import as either a salesreceipt or a salesorder.  It uses a library called cv3go.  You can use the official version at - https://github.com/cv3/cv3go  or the forked version referenced in the code at - https://github.com/amazingfly/cv3go  (the reference to this library will be vendored in future versions, or the forked version will be merged in)
